

#' @param last_year list with two elements, state and changes, as generated by ham_year
ham_ui <- function(last_year, y = 0){
  
  #-----------------report on the current state and what happened last year-------------------
  mess <- "================================\nHammurabi, I beg to report to you:\n\n"
  mess <- paste0(mess, "In the year ", y, ", ", last_year$changes$starved, " people starved.\n")
  mess <- paste0(mess, last_year$changes$new_people, " people came to the city.\n")
  if(last_year$changes$plague_people > 0){
    mess <- paste0(mess, "A terrible plague struck! ", last_year$changes$plague_people, " perished. Sad!\n")
  }
  mess <- paste0(mess, "The city population is now ", last_year$state$people, ".\n\n")
  mess <- paste0(mess, "The city now owns ", last_year$state$acres_owned, " acres.\n\n")
  mess <- paste0(mess, "You harvested ", last_year$changes$yield, " bushels per acre.\n")
  mess <- paste0(mess, "Rats ate ", last_year$changes$rats_eaten, " bushels.\n")
  mess <- paste0(mess, "You now have ", last_year$state$bushels_store, " bushels in store.\n\n")
  
  #----------------input what you want to do now-------------
  price <- sample(17:26, 1)
  mess <- paste0(mess, "Land is trading at ", price, " bushels per acre.\n\n")
  
  cat(mess)
  
  cat("How many acres do you wish to buy?\n")
  buy <- as.numeric(readLines(n = 1))
  cat("\nHow many acres do you wish to sell?\n")
  sell <- as.numeric(readLines(n = 1))
  
  acres <- last_year$state$acres_owned + buy - sell
  bushels <- last_year$state$bushels_store - buy * price + sell * price
  cat("\nYou now have", bushels, "bushels and", acres, "acres.\n")
  
  
  cat("\nHow many bushels do you wish to feed your people?\n")
  feed <- as.numeric(readLines(n = 1))
  while(feed > bushels){
    message("You don't have enough bushels for that... Pathetic!")
    feed <- as.numeric(readLines(n = 1))
  }
  
  cat("\nHow many acres do wish to plant, at one bushel per acre?\n")
  plant <- as.numeric(readLines(n = 1))
  while(plant > acres){
    message(paste("But you only have", acres, "acres..."))
    plant <- as.numeric(readLines(n = 1))
  }
  
  while(plant > last_year$state$people * 10){
    message(paste("But you only have", last_year$state$people, "people to tend the field..."))
    plant <- as.numeric(readLines(n = 1))
  }        
  while(plant > bushels - feed){
    message(paste("But you only have", bushels - feed, "bushels left..."))
    plant <- as.numeric(readLines(n = 1))
  }
  
    
  state <- list(
    acres_owned = acres,
    acres_planted = plant,
    people = last_year$state$people, # you can't buy or sell people
    bushels_fed = feed,
    bushels_store = bushels - feed - plant 
  )
  
  return(state)
}


hamurabi <- function(){
  starting_state <- list(
    state = list(acres_owned = 1000, acres_planted = 0, people =100, bushels_fed = 0, bushels_store = 2800),
    changes = list(yield = 3, rats_eaten = 0, new_people = 5, starved = 0, plague_people = 0))
  
  latest_state <- ham_year(ham_ui(starting_state, y = 0))
  for(i in 1:10){
    latest_state <- ham_year(ham_ui(latest_state, y = i))
  }
}

hamurabi()
