
#' Input from user
#' 
#' Input from user and some basic acceptance checks
#' 
.input <- function(){
  x <- readLines(n = 1)
  if(x %in% c("q", "Q", "quit", "exit")){
    stop("Exiting due to user grumpiness")
  }
  while(is.na(as.numeric(x))){
    message("Your response must be numeric")
    x <- .input()
  }
  while(as.numeric(x) < 0){
    message("Your response must be more than zero")
    x <- .input()
  }
  return(as.numeric(x))
}

#' Report the state of the city
#' 
#' Report the state of the city for a given year
#' @param last_year list with two elements, state and changes, as generated by ham_year
#' @param y year
ham_report <- function(last_year, y = 0){
  
  #-----------------report on the current state and what happened last year-------------------
  mess <- "================================\nHammurabi, I beg to report to you:\n\n"
  mess <- paste0(mess, "In the year ", y, ", ", last_year$changes$starved, " people starved.\n")
  mess <- paste0(mess, last_year$changes$new_people, " people came to the city.\n")
  if(last_year$changes$plague_people > 0){
    mess <- paste0(mess, "A terrible plague struck! ", last_year$changes$plague_people, " perished. Sad!\n")
  }
  mess <- paste0(mess, "The city population is now ", last_year$state$people, ".\n\n")
  mess <- paste0(mess, "The city now owns ", last_year$state$acres_owned, " acres.\n\n")
  mess <- paste0(mess, "You harvested ", last_year$changes$yield, " bushels per acre.\n")
  mess <- paste0(mess, "Rats ate ", last_year$changes$rats_eaten, " bushels.\n")
  mess <- paste0(mess, "You now have ", last_year$state$bushels_store, " bushels in store.\n\n")
  
  mess <- gsub(" 1 people", "1 person", mess)
  mess <- gsub("^1 people", "1 person", mess)
  mess <- gsub("1 bushels", "1 bushel", mess)
  
  cat(mess)
}

#' A year of inputs
#' 
#' Prompt and accept a year's worth of decisions from the Hamurabi player     
#' @param last_year list with two elements, state and changes, as generated by ham_year  
#' @param y year
ham_inputs <- function(last_year, y = 0){  
  #----------------input what you want to do now-------------
  price <- sample(17:26, 1)
  mess <- paste0("Land is trading at ", price, " bushels per acre.\n\n")
  
  cat(mess)
  
  cat("How many acres do you wish to buy?\n")
  buy <- .input()
  cat("\nHow many acres do you wish to sell?\n")
  sell <- .input()
  
  acres <- last_year$state$acres_owned + buy - sell
  bushels <- last_year$state$bushels_store - buy * price + sell * price
  cat("\nYou now have", bushels, "bushels and", acres, "acres.\n")
  
  
  cat("\nHow many bushels do you wish to feed your people?\n")
  feed <- .input()
  while(feed > bushels){
    message("You don't have enough bushels for that... Pathetic!")
    feed <- .input()
  }
  
  cat("\nHow many acres do wish to plant, at one bushel per acre?\n")
  plant <- .input()
  while(plant > acres){
    message(paste("But you only have", acres, "acres..."))
    plant <- .input()
  }
  
  while(plant > last_year$state$people * 10){
    message(paste("But you only have", last_year$state$people, "people to tend the fields..."))
    plant <- .input()
  }        
  while(plant > bushels - feed){
    message(paste("But you only have", bushels - feed, "bushels left as seed..."))
    plant <- .input()
  }
  
    
  state <- list(
    acres_owned = acres,
    acres_planted = plant,
    people = last_year$state$people, # you can't buy or sell people
    bushels_fed = feed,
    bushels_store = bushels - feed - plant 
  )
  
  return(state)
}

#' Play the Hamurabi game
#' 
#' Human interface to play the Hamurabi city management game
#' 
#' @export
#' @param years length of term
#' @return None.  This function is called for its side effect of playing a game.
hamurabi <- function(years = 10){
  starting_state <- list(
    state = list(acres_owned = 1000, acres_planted = 0, people =100, bushels_fed = 0, bushels_store = 2800),
    changes = list(yield = 3, rats_eaten = 0, new_people = 5, starved = 0, plague_people = 0))
  
  prop_starved <- rep(NA, years)
  num_starved <- rep(NA, years)
  
  #---------year 0------------
  ham_report(starting_state, y = 0)
  latest_state <- ham_year(ham_inputs(starting_state, y = 0))
  prop_starved[1] <- latest_state$changes$prop_starved
  num_starved[1] <- latest_state$changes$starved
  
  #---------years 1 to 9--------------
  i <- 0
  while(i < (years - 1) & max(prop_starved, na.rm = TRUE) < 0.45){
    i <- i + 1
    ham_report(latest_state, y = i)
    latest_state <- ham_year(ham_inputs(latest_state, y = i))
    prop_starved[i + 1] <- latest_state$changes$prop_starved
    num_starved[i + 1] <- latest_state$changes$starved
  }
  
  #----------final report----------
  # standard report on the last year:
  ham_report(latest_state, y = i + 1)
  
  av_prop_starved <- mean(prop_starved, na.rm = TRUE)
  av_acres <- latest_state$state$acres_owned / latest_state$state$people
  
  
  mess <- "\n============================\n\nLet's sum up here.\n\n"
  mess <- paste0(mess, "In your ", i + 1, "-year term of office, ", round(av_prop_starved * 100), 
                 " percent of the population starved per year on average.\n")
  mess <- paste0(mess, "That means, a total of ", sum(num_starved, na.rm = TRUE), " people died!\n\n")
  mess <- paste0(mess, "You started with ", 
                 round(starting_state$state$acres_owned / starting_state$state$people, 1),
                 " acres per person and ended with ",
                 round(av_acres, 1),
                 " acres per person.\n\n")
  
  if(av_prop_starved > 0.33 | av_acres < 7 | max(prop_starved) > 0.45){
    # dreadful
    mess <- paste0(mess, "Due to this extreme mismanagement you have not only\nbeen impeached and thrown out of office but you have\nalso been declared 'National Fink'!!\n")
  } else {
    if (av_prop_starved > 0.1 | av_acres < 9){
      # bad
      mess <- paste0(mess, "Your heavy handed performance smacks of Nero and Ivan IV.\nThe people (remaining) find you an unpleasant ruler, and\nfrankly, hate your guts!\n")
    } else {
      if (av_prop_starved > 0.03 | av_acres < 10){
        # mediocre
        mess <- paste0(mess, "Your performance could have been somewhat better, but\nreally wasn't too bad at all.\n")
        mess <- paste0(round(latest_state$state$population * runif(1)), " would dearly love to see you assassinated but we all have our little problems.")
      } else {
        # fantastic
        mess <- paste0(mess, "A fantastic performance!!! Charlemagne, Disraeli and \nJefferson combined could not have done better!")
      }
    }
  }

  cat(mess)
}

